### ISSUE TITLE
[Phase 4] GitHub Actions自動実行とS3デプロイ機能の実装

### ISSUE THREAD

**Issue by okawak** [okawak/okawak_blog#7]
Rustコードから直接S3アップロードするのではなく、GitHub Actionsでcron実行し、submoduleからHTMLを生成してS3にアップロードする機能を実装します。

## 前提条件
- Issue #6（Bookmark変換）が完了していること
- GitHub Actionsの実行環境が設定されていること

### 1. Rustプログラムの修正
```rust
// S3アップロード機能を削除し、ローカル出力のみに変更
pub fn run_main(config: Config) -> Result<()> {
    // 1. Obsidian submoduleからファイル取得
    // 2. HTML変換処理
    // 3. dist/ディレクトリへの出力のみ
    // 4. S3アップロード機能は削除
}
```

### 2. GitHub Actions Workflow設定
```yaml
# .github/workflows/deploy.yml
name: Deploy Obsidian to S3
on:
  schedule:
    - cron: '0 0 * * *'  # 毎日00:00 UTC
  workflow_dispatch:     # 手動実行可能

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # submodule取得
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Build obsidian_uploader
        run: cargo build --release -p obsidian_uploader
        
      - name: Run obsidian_uploader
        run: cargo run --release -p obsidian_uploader
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          
      - name: Sync to S3
        run: |
          aws s3 sync crates/obsidian_uploader/dist s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --content-type "text/html; charset=utf-8"
```

### 3. Submodule管理機能
- [ ] Obsidian submoduleの自動更新
- [ ] submodule内のファイル変更検出
- [ ] 増分処理のための変更追跡

### 4. GitHub Secrets設定
```bash
# 必要なSecrets
AWS_REGION=ap-northeast-1
AWS_ROLE_ARN=arn:aws:iam::ACCOUNT:role/github-actions-role
S3_BUCKET_NAME=your-blog-bucket
```

### 5. ログ・モニタリング機能
- [ ] GitHub Actions実行ログの詳細化
- [ ] 処理結果のサマリー出力
- [ ] エラー時の通知機能（GitHub Issues作成等）

### 6. テストケース
- [ ] GitHub Actions workflowのテスト
- [ ] submodule取得のテスト
- [ ] AWS CLI同期処理のテスト

## 成功条件
- [ ] cron実行でObsidianコンテンツが自動更新される
- [ ] submoduleの変更が正しく反映される
- [ ] S3への同期が確実に実行される
- [ ] 実行ログが適切に出力される

## 推定工数
2-3日

## 依存関係
- Issue #6
